### PR TITLE
ROS 2

### PR DESCRIPTION
**Pull request by sacovo**
I managed to compile and run the software on ros2, but I'm not happy yet with the results, but I'm not sure what the issue is. I can start it up, with the euroc_mav configuration. And then I start to play one of the rosbags, and it starts tracking and also publishes results. But the results are way off, and the covariances are huge.

Maybe I'm doing something wrong with setting the whole thing up, or there seems to be an issue with something I changed in order to make it build on ros2.

I don't have a ros1 setup to compare, which makes this a bit harder.

### CODE REVIEW

**Comment by jacob-02** [comment]
Could you also provide an edited readme on how to use this ROS2 port for the example files mentioned?

Thank you

**Comment by sacovo** [comment]
Hi, I've been using this branch for other stuff, so I'll close this PR and open a new one with a clean history and I'll include a Readme as well. 

I'll close this PR and open a new one, I guess I should be able to do this over the weekend.

**Comment by jacob-02** [comment]
Hey, any updates on this regards?

Thanks in advance

**Comment by sacovo** [comment]
See: #38

**Pull request closed without merging**
